  import type { Metadata } from "next";
  import { Geist, Geist_Mono } from "next/font/google";
  import { ClerkProvider } from '@clerk/nextjs'
  import "./globals.css";
  import TopNav from "@/components/nav/top-nav";
  import { ThemeProvider } from "@/context/theme-provider";
  import { UsageProvider } from "@/context/usage";


  const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
  });

  const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
  });

  export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
  };

  export default function RootLayout({
    children,
  }: Readonly<{
    children: React.ReactNode;
  }>) {
    return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`} >
            <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
      <UsageProvider>
      <header><TopNav/></header>
      <main>{children}</main>
      </UsageProvider>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
    );
  }
